### ISSUE TITLE
"wrong type" error in gs_import_gtfs

### ISSUE THREAD

**Issue by GraemeBrown** [graphserver/graphserver#16]
I receive the error pasted below using gs_import_gtfs. The min_transfer_time field in the gtfsdb is  floating data type, but I think the code is looking for a long integer.

Graeme

Loading transfers to graph...
Traceback (most recent call last):
  File "/usr/local/bin/gs_import_gtfs", line 9, in <module>
    load_entry_point('graphserver==0.1', 'console_scripts', 'gs_import_gtfs')()
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/compiler/gdb_import_gtfs.py", line 257, in main
    gdb_load_gtfsdb( gdb, options.namespace, gtfsdb, gdb.get_cursor(), agency_id, maxtrips=maxtrips)
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/compiler/gdb_import_gtfs.py", line 212, in gdb_load_gtfsdb
    for fromv_label, tov_label, edge in compiler.gtfsdb_to_edges( maxtrips ):
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/compiler/gdb_import_gtfs.py", line 204, in gtfsdb_to_edges
    for edge_tuple in self.gtfsdb_to_transfer_edges():
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/compiler/gdb_import_gtfs.py", line 192, in gtfsdb_to_transfer_edges
    yield (s1, s2, int(ElapseTime(min_transfer_time)))
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/core.py", line 1143, in **init**
    self.soul = self._cnew( seconds )
ctypes.ArgumentError: argument 1: <type 'exceptions.TypeError'>: wrong type

**Comment by bmander** [comment]
Which feed is provoking this problem?

**Comment by bmander** [comment]
9689b708a9d6a890af941b156d17ac1d34d3499d
