### ISSUE TITLE
gs_routeserver example throws error

### ISSUE THREAD

**Issue by ccoffey** [graphserver/graphserver#17]
The example http://localhost/path?origin=%22osm-92011649%22&dest=%22sta-3803%22&currtime=1260839444 throws the below error.

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/servable-2009b-py2.6.egg/servable.py", line 105, in myapp
    rr = xstr( pfunc(self,**args) )
  File "/usr/local/lib/python2.6/dist-packages/graphserver-0.1-py2.6.egg/graphserver/ext/routeserver/routeserver.py", line 139, in path
    vertices, edges = spt.path( dest )
AttributeError: 'NoneType' object has no attribute 'path'

**Comment by bmander** [comment]
529038004c58c94d35c2199e49a7b346e513424b
